### ISSUE TITLE
Horizontal scroll not working in nested element

### ISSUE THREAD

**Issue by pablomercadolibre** [theKashey/react-remove-scroll#10]
Hi @theKashey , first of all i want to tank you for all your work, with that said, i'm using `react-remove-scroll` and it work's great when the element inside RemoveScroll has vertical scroll but i've one case where the element have horizontal scroll(just a div with overflow-x: scroll) and in that case it works using chrome emulator but in a real device e.g iphone 6+ it does not, the touch move event is canceled stoping the scroll, maybe i'm doing something wrong or maybe is a known limitation ?

btw, i'm using `react-remove-scroll` through `react-focus-on` but i've tried with this package in isolation and i'm experiencing the same issue

i put an example together https://codesandbox.io/s/musing-swanson-ds69w

Thanks!

**Comment by theKashey** [comment]
You are right - that’s a limitation of the current implementation. Going to fix it in the next release

**Comment by pablomercadolibre** [comment]
Great, looking forward for the next release, thanks!
