### ISSUE TITLE
Can't edit selection in a textarea (iOS 17)

### ISSUE THREAD

**Issue by omeralpi** [theKashey/react-remove-scroll#101]
### Bug report
In iOS 17, I am unable to edit the selection (move the little points around) in a textarea, whereas there is no issue in iOS 16.4.

### Current Behavior
Can't edit selection in a textarea (iOS 17)
https://github.com/theKashey/react-remove-scroll/assets/19254700/3c96a0b8-affb-4c67-bbf6-df9d095ed05f

### Expected behavior
Should be able to edit selection iOS 17

### Reproducible example
https://codesandbox.io/s/react-remove-scroll-bug-2w4d2p

**Comment by Cuzart** [comment]
This is still an active issue and is not fixed by #110 can we reopen this ?
