### ISSUE TITLE
"Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'." when placed inside a shadow root

### ISSUE THREAD

**Issue by PottyZA** [theKashey/react-remove-scroll#108]
Similar to #89, if the `<RemoveScroll>` component is used inside a shadow root, the code inside `elementCanBeScrolled` can sometimes fail with the error message: 
```
"Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."
```

For example, when using `@radix-ui/react-dialog` (version `1.0.6-rc.5`), which uses `react-remove-scroll@2.5.7` (the error also occurs if you force `2.5.9`), if you attempt to scroll inside a shadow root when scrolling should be disabled (ie. if the content is not overflowing), then the error above is raised.

This could possibly be due to the shadow root not being an actual element. After some testing, it appears that this can be fixed by adding the following code to `elementCanBeScrolled()`:
```
if (!(node instanceof HTMLElement)) return false
```

**Comment by theKashey** [comment]
v2.5.10 was released with the fix.

However, I need to point out that the code responsible for the same behaviour was already in place, including a use case in a storybook representing "lock in a shadow dom" example. 

I failed to reproduce the problem and it's unclear what exactly is happening here. `parameter 1 is not of type 'Element'`, but it's not `ShadowRoot` as well. 
Only you can confirm the fix and clarify the original problem.

**Comment by Pavel-Liteiniy** [comment]
Hey @theKashey, I've just faced the same issue in react-remove-scroll@2.7.1

<img width="1969" height="460" alt="Image" src="https://github.com/user-attachments/assets/3ae987d8-00fa-42a0-b33d-455b4083b393" />

<img width="1072" height="906" alt="Image" src="https://github.com/user-attachments/assets/00d105d1-8d92-4512-9bf0-16978a2c57a2" />

**Comment by yfs-2000** [comment]
I also encountered this problem in version 2.7.1.
