### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by TrevorRice** [theKashey/react-remove-scroll#111]
Hi all!

With the [upcoming release of React 19](https://react.dev/blog/2024/04/25/react-19), are there any plans to update `react-remove-scroll` to be React 19 compatible (once available)? I'm thinking specifically of the package's [peerDependency list](https://github.com/theKashey/react-remove-scroll/blob/8923c513d269190162eb4678c1b80137f5998679/package.json#L50-L51) and its exported types.

This is basically a duplicate of the [issue I created for `react-focus-lock`](https://github.com/theKashey/react-focus-lock/issues/320).

Cheers!

**Comment by theKashey** [comment]
👍 Better be prepared
