### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by infodusha** [theKashey/react-remove-scroll#122]
It would be really cool if you would allow react 19 in `package.json`
Also probably worth to allow `^19.0 || ^19.0.0-rc` as next 15 gone stable with react 19 rc version

**Comment by cloetensbrecht** [comment]
`react-remove-scroll@2.6.0" has incorrect peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0"`
Please add support for React 19

**Comment by jantimon** [comment]
@theKashey we can't upgrade our [fumadocs](https://fumadocs.vercel.app/) because react-remove-scroll does not support react 19

**Comment by theKashey** [comment]
Sorry for the delay. Likely this time updated all related pieces to unblock React 19
