### ISSUE TITLE
Unable to drag Plotly js rangeslider

### ISSUE THREAD

**Issue by Lexachoc** [theKashey/react-remove-scroll#123]
Hi, I'm using [Radix Dialog](https://www.radix-ui.com/primitives/docs/components/dialog), and it use this library under the hood when `modal={true}` (default for Dialog).

I have posted in [here](https://github.com/radix-ui/primitives/issues/3222) about the issue. but I assume this is due to the lock of events of this library. So I open an issue in here.

### Reproducible example
The plot outside the Dialog is fine, both the range slider and the plot can be dragged. But the range slider of the plot inside the Dialog cannot be dragged and causes an error (from Plotly).

https://codesandbox.io/p/sandbox/plotly-inside-dialog-7vlg2r

The `style="pointer-events: none;"` on `body` is not allowing me to drag the rangeslider inside the Dialog.

**Comment by theKashey** [comment]
👋 `pointer-events` are restored back to `all` for the modal and should not affect anything, but (thank you for the example) they do. Not sure how, but if I remove inline style from the body - everything works.  If I dont, then it crashes as you said.

Reason is yet unknown

**Comment by theKashey** [comment]
However there is one moment that is a little suspicious - this library is never setting `pointer-events` as inline style, that is actually [Radix doing](https://github.com/radix-ui/primitives/blob/4584a37bfa239c390b516282290cde882dd3af19/packages/react/dismissable-layer/src/DismissableLayer.tsx#L117). 
My approach here is [to work via classes](https://github.com/theKashey/react-remove-scroll/blob/2aa31bcd60b47910ec75a109e6a684e5ba30969f/src/SideEffect.tsx#L21), and these classes will only be added if `inert` attribute is set.

May be the ball is still on the Radix side

**Comment by Lexachoc** [comment]
Thank you for digging into the cause! That's very helpful to know what's going on.

I will close this issue then, since the inline style was introduced by Radix and not this library.

I’ll follow on the issue report on Radix side then.

Thank you very much!

**Comment by theKashey** [comment]
You are always welcome
