### ISSUE TITLE
Scroll is blocking when touching top on firefox and safari on macOS

### ISSUE THREAD

**Issue by maru3l** [theKashey/react-remove-scroll#16]
The scroll is making a weard block on Firefox and Safari on macOS when I'm scrolling to the top or the bottom of the children element.

The worst is with Firefox. The screen is locked for half a second and scroll after.

You can reproduce here:
 - Go to [https://deploy-preview-2--larteredanse.netlify.com/](https://deploy-preview-2--larteredanse.netlify.com/) with Firefox.
 - Scroll down the page a little bit, you gonna see a menu disappear in the right corner and a Menu button appeared, click on the menu button.
 - Scroll in the fullscreen back and forward on the menu, you gonna see the issue when the screen arrives to top or to the bottom.

This is the code of the header [https://github.com/maru3l/lartere-danse/blob/feat/add-pages/www/src/components/SiteHeader/SiteHeader.jsx](https://github.com/maru3l/lartere-danse/blob/feat/add-pages/www/src/components/SiteHeader/SiteHeader.jsx)

**Comment by theKashey** [comment]
Found the root cause - wheel event is not becoming a scroll event. Mostly related to the momentum scroll...

**Comment by theKashey** [comment]
next version would contain __undocumented__ property `noOverscroll`, which would solve your case.
I need some time to collect more information about how scroll blocking actually _should_ work, and probably would do `noOverscroll` a default behaviour - for now, it works for 100% of my cases, and in all browsers, I've yet tested.

**Comment by theKashey** [comment]
Upd: 2.1.1 comes with mended behaviour by default.

**Comment by shredor** [comment]
Hello!
I ran into the same problem. When I scroll the popup window quickly up and down on Firefox using long separate swipes on trackpad, the scroll is delayed for half a second when I reach  top/bottom edge.
This bug also exists at https://deploy-preview-2--larteredanse.netlify.com/ (however it uses 2.1.1)

**Comment by theKashey** [comment]
It's the same issue with the "momentum scroll". It's _dead_ till the end of inertia animation - up to 2 seconds.
I was trying to mitigate it in different ways, without much luck.
