### ISSUE TITLE
Adds 8px padding to body

### ISSUE THREAD

**Issue by jancama2** [theKashey/react-remove-scroll#18]
I don't know why it happens but when I'm rendering RemoveScroll into portal 
```
<div id="root"/>
<div id="modal"/> // here is the remove scroll
```
it doesn't add padding to body.

If I render it not in modal back in the root of the react app:
```
<div id="root">
  <div id="modal /> // here is the remove scroll
</div>
```
it add padding 8px to body, but it breaks my styles.

Why is this happening? Tried to debug the library, but haven't found any place where the styles for body are added.

**Comment by jancama2** [comment]
My bad, it is made by the `remove-scroll-bar` package

**Comment by theKashey** [comment]
It "compensates" removed scrollbar.
