### ISSUE TITLE
Does not play well with react-popper

### ISSUE THREAD

**Issue by SapienTech** [theKashey/react-remove-scroll#19]
hi @theKashey thank you first of all for the amazing work you have done with the react-focus-on ecosystem.

So trying to build a pop-over with react-popper (for popper positioning), and react-focus-on (for focus-lock, scroll-lock etc), but noticed some rendering issues when they are implemented together.

Here is the react-popper by itself:
```jsx
<Manager>
  <Reference>{({ref}) => <button ref={ref}>Trigger</button>}</Reference>
  <Popper placement="top">
    {({placement, ref, style}) => (
      <div ref={ref} data-placement={placement} style={style} tabIndex={0}>
        <span>Popover Content</span>
      </div>
    )}
  </Popper>
</Manager>;

```
which outputs 
<img width="189" alt="image" src="https://user-images.githubusercontent.com/8230000/70386704-cc118600-1950-11ea-9683-a80228a57906.png">
which is expected: the popover content is positioned right above the trigger.

Simply adding focus-on, however:
```jsx
<Manager>
  <Reference>{({ref}) => <button ref={ref}>Trigger</button>}</Reference>
  <Popper placement="top">
    {({placement, ref, style}) => (
      <FocusOn>
        <div ref={ref} data-placement={placement} style={style} tabIndex={0}>
          <span>Popover Content</span>
        </div>
      </FocusOn>
    )}
  </Popper>
</Manager>;
```
produces this:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/8230000/70386723-f5caad00-1950-11ea-9af0-ae638f52b06e.png">

it appears react-popper is unable to do its positioning magic...

After doing some digging, i found that simply disabling scroll-lock fixes the issue!
```jsx
<Manager>
  <Reference>{({ref}) => <button ref={ref}>Trigger</button>}</Reference>
  <Popper placement="top">
    {({placement, ref, style}) => (
      <FocusOn scrollLock={false}>
        <div ref={ref} data-placement={placement} style={style} tabIndex={0}>
          <span>Popover Content</span>
        </div>
      </FocusOn>
    )}
  </Popper>
</Manager>;
```
<img width="189" alt="image" src="https://user-images.githubusercontent.com/8230000/70386830-91a8e880-1952-11ea-9bb0-46d1f6d3886d.png">

Do you think react-remove-scroll is at fault here, maybe being to restrictive, or do you think popper.js is at fault. Im happy to reach out to react-popper/popper.js communities too, but thought i would start with a post here to see if you had some helpful context.

Thank you very much!
Dylan

**Comment by SapienTech** [comment]
@theKashey after a bit more investigation, turns out there was a global reset file getting in the way of everything. im going to close this :)

**Comment by theKashey** [comment]
👍 👍 👍 
Have a good day :)
