### ISSUE TITLE
How to allow scroll on multiple elements?

### ISSUE THREAD

**Issue by dotmlj** [theKashey/react-remove-scroll#20]
Hi.

How is it possible to allow scroll on multiple elements?

The doc mentions "support nested scrollable elements" and "More than one lock" but I don't see/understand how it's done.

Thank you! :)

**Comment by theKashey** [comment]
Oh, that's really is not explained in the documentation.
But there is a `shards` prop, where you can provide an array of Refs to "other elements"
```
const ref = useRef();

<div ref={ref}>Some location</div>
<RemoveScroll ref={[ref]}>Work for "Some Location", as well as for own children</RemoveScroll>
```
👉 keep in mind, `shards` are not "portal-friendly"

**Comment by dotmlj** [comment]
Thank you for the fast reply, it works! :)

For future reference here's how I made it:

```
class Details extends React.Component {
  constructor(props) {
    this.firstScrollElement = React.createRef();
  }

...

<div className={classes.scroll} ref={this.firstScrollElement}>
    children
</div>

<RemoveScroll shards={[this.firstScrollElement]} className={classes.scroll}>
    children
</RemoveScroll>
```

Notice that "ref" on <RemoveScroll> in @theKashey example should of course be "shards".

**Comment by theKashey** [comment]
Yep, of course "shards" 😅
