### ISSUE TITLE
docs are backward

### ISSUE THREAD

**Issue by sophiagatliff** [theKashey/react-remove-scroll#22]
"Just wrap content, which should be scrollable, and everything else would not."
```
import {RemoveScroll} from 'react-remove-scroll';

<RemoveScroll>
  Only this content would be scrollable
</RemoveScroll>  
```

It works the other way yes? the children of RemoveScroll are NOT scrollable.

**Comment by theKashey** [comment]
Look like the name of a component is not that correct, but it really allows scrolling only __inside__, and suppresses any scroll __outside__.

So docs are _forward_ :)
