### ISSUE TITLE
Scroll delay on MacOS Firefox

### ISSUE THREAD

**Issue by shredor** [theKashey/react-remove-scroll#23]
Hi!
When I scroll the popup window quickly up and down on MacOS Firefox using long separate swipes on trackpad, the scroll is delayed for half a second when I reach  top/bottom edge.
This bug exists at https://deploy-preview-2--larteredanse.netlify.com/ (however it uses 2.1.1)

_Originally posted by @shredor in https://github.com/theKashey/react-remove-scroll/issues/16#issuecomment-613466603_

**Comment by theKashey** [comment]
In the majority of cases, when the closest scrollable parent for `locks` is `document.body`, scrolling of which is cancelled via `css`, this should not be an issue (theoretically).

More investigations are required.
