### ISSUE TITLE
Listening to the scroll event of <RemoveScroll>

### ISSUE THREAD

**Issue by gun0317** [theKashey/react-remove-scroll#30]
Hi, 
I'd like to listen to the scroll event (`addEventListener('scroll', handler)`) of a popup to detect if the user is scrolling up or down.
If I use `<RemoveScroll>` however, it seems like that `scroll` event is not happening cause I obviously locked the `scroll` of parent component.

How can I detect whether the user is scrolling down or up that is happening inside the `<RemoveScroll>` but not in the parent component?

ps. I'm using the following code to detect whether the user is scrolling up/down.

```
const useDetectScrollingDown = () => {
  const [isScrollingDown, setIsScrollingDown] = useState(false)

  useEffect(() => {
    let prevScrollY = window.pageYOffset
    const handleScroll = () => {
      window.pageYOffset > prevScrollY ? setIsScrollingDown(true) : setIsScrollingDown(false)
      prevScrollY = window.pageYOffset
    }
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  return isScrollingDown
}
```

**Comment by theKashey** [comment]
`window.addEventListener('scroll', handleScroll, true)` - use `capture` to listen to event when it is going down to the target node, and _not yet_ has been prevented.
> don't forget to update removeEventListener as well

**Comment by gun0317** [comment]
@theKashey  
I used `capture` to be true to listen to the `scroll` event as you said and it does listen to the event. 
However since the scroll of window (`window.pageYOffset`) is not changing, the value pageYOffset is same and I cannot decide if the user is scrolling up/down. Can there be any solution?

**Comment by theKashey** [comment]
Well, you obviously should not look at `window.pageYOffset`. There are few different options:
- listen to `wheel` event (and `touchmove`). However, you will have to manually detect "if" that event will cause a scroll. (this is basically what this package is doing)
- listen to `scroll` event, and compare `event.target.scrollTop` to previous "known" value. You might know it, if there is only one "scrollable" div you are interested in (then you might attach `onScroll` handled to it)

Both variants do not sound as something simple. So let's start from scratch - what you want to do?

**Comment by gun0317** [comment]
@theKashey 
What I wanted to do was catching the scroll event inside `<RemoveScroll>`.

>listen to scroll event, and compare event.target.scrollTop to previous "known" value. You might know it, if there is only one "scrollable" div you are interested in (then you might attach onScroll handled to it)

This solves the problem! Thank you so much 👍
