### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by jamesplease** [theKashey/react-remove-scroll#31]
Hi again @theKashey ! I _also_ love this lib. I'm opening this issue just to server as a place to track updating this lib to React 17. I might have to time to look into this but I can't commit to that right now ✌️ 

Anyway, cheers!

**Comment by theKashey** [comment]
For context: React dependency has been updated to include 17 as well, but as long as 17 also changed the way events are propagated through portals - some stuff is yet to double-check and fix.

**Comment by jamesplease** [comment]
Closing 'cause this seems to be fixed. Thanks a ton @theKashey and anyone else who may have contributed to update this lib!
