### ISSUE TITLE
Scroll not locked when moving mouse out of window after scroll (Chrome, macOS)

### ISSUE THREAD

**Issue by karlhorky** [theKashey/react-remove-scroll#4]
First of all, thanks for this project! It seems to work well in most cases.

One case where it doesn't work is the following (admittedly, an edge case):

1. Scroll a lot with a mouse/setup that allows acceleration scrolling (ex. I have a Magic Mouse)
2. Move mouse outside of window quickly afterwards
3. Watch the locked background scroll with the left over acceleration

![Kapture 2019-05-03 at 13 34 44](https://user-images.githubusercontent.com/1935696/57135091-9009b780-6da8-11e9-8869-ae83d922e8cd.gif)

**Comment by theKashey** [comment]
Try again:
What I did:
- on "scrollbar-free" Systems, like OSx or mobiles, I was not hiding scroll bars as long as they should not be visible in any case. But they were.
- now scrollbars would be hidden in any case.

I am looking forward to the mix of old and new behaviour for #3, including controlling scrollbars existence for all parents. That was a problem - you were able to bypass `scroll-lock` using _momentum scrolling_.

**Comment by karlhorky** [comment]
Cool, thanks for the quick response! Will test and report back.

**Comment by karlhorky** [comment]
@theKashey Seems like it is fixed with your commit c9c320935c5cb0adb277d7dd5359295b80b6bf52 🎉 Nice work.

Closing this issue now.
