### ISSUE TITLE
RemoveScroll is broken inside a shadow dom

### ISSUE THREAD

**Issue by circlingthesun** [theKashey/react-remove-scroll#45]
Elements inside of RemoveScroll doesn't scroll when React is mounted inside a shadow dom. I've reproduced the issue here:

https://codesandbox.io/s/cranky-solomon-ox8po?file=/src/App.js

**Comment by EyMaddis** [comment]
Same for the other way around. If the scrollable area is inside a custom element with shadow DOM with is a child of RemoveScroll, it won't work.

**Comment by theKashey** [comment]
Thanks for the use case easy to reproduce. It's not clear which logic is preventing the scroll, but there are a few places obviously not compatible with shadow dom concepts.

**Comment by austintackaberry** [comment]
I believe I have also run into this issue using chakra modal in a shadow dom

**Comment by sandro768** [comment]
using radix-ui/react-select in shadow dom and having the same issue

**Comment by theomessin** [comment]
This is still an issue 😭

**Comment by nwilkie07** [comment]
I am also having this issue. When attempting to remove scroll from everything outside of a dropdown component It removes scroll on the conditionally mounted dropdown component.

**Comment by reify-benjamin-solum** [comment]
Also having this issue.

**Comment by pethel** [comment]
Still a problem here

**Comment by theKashey** [comment]
Can anyone give me a hand? 🙏 
Any help would be quite appreciated.

**Comment by csorfab** [comment]
> Can anyone give me a hand? 🙏 Any help would be quite appreciated.

@theKashey Hi, I think I managed to fix this in PR #97

**Comment by theKashey** [comment]
Update example provided by @circlingthesun to use v.**2.5.7** - https://codesandbox.io/s/dreamy-paper-dd269d 
And look like it solves the problem.

All kudos goes to @csorfab, without their efforts this issue will be unsolved for another year 👏
