### ISSUE TITLE
Not working on Safari iOS 15

### ISSUE THREAD

**Issue by erasmo-marin** [theKashey/react-remove-scroll#52]
On the latest iOS version, Safari moved the toolbar to the bottom and now this library is not working for me. I think the solution should be easy, prevent the default action for the `pointermove` event is needed now, adding that should do the trick.

**Comment by theKashey** [comment]
Checked and _everything_ seems to be working - there is no page scroll. 
However 🥲, I can see toolbar moving as I touch (with no reaction to the touch) my page and something should be changed.

Thanks for letting me know

**Comment by erasmo-marin** [comment]
Yeah, sorry If I was not clear enough, I mean the toolbar behavior. I tried to patch it with no luck, sorry :C
