### ISSUE TITLE
Horizontal scroll disabled on nested slider

### ISSUE THREAD

**Issue by iamhosseindhv** [theKashey/react-remove-scroll#59]
Thanks for the great library.

I have been using reach ui [slider](https://reach.tech/slider) inside a `RemoveScroll` component, and on mobile touch devices (I've personally tested it on Safari), the touch event is disabled.

I've noticed this is also the case with a simple `<input type="range" />` element nested inside `RemoveScroll`.

### Steps to reproduce
1. View link on a mobile device https://codesandbox.io/s/sharp-payne-fd1kfb?file=/src/App.tsx
2. You won't be able to move the slider knob if RemoveScroll is `enabled`. (see gif below). When scroll lock is enabled, I'm unable to move the slider.

Here's a related issue: https://github.com/reach/reach-ui/issues/678

![RPReplay_Final1645012444](https://user-images.githubusercontent.com/26996372/154259903-08601e9f-41f1-4f51-b96c-1ffe61135c61.gif)

**Comment by theKashey** [comment]
Strange. https://github.com/theKashey/react-remove-scroll/pull/34 should have range inputs fixed.

**Comment by theKashey** [comment]
Range inputs were fixed for #64. 2.5.1+ version should have corrected behavior
