### ISSUE TITLE
allow removal of scroll from entire page

### ISSUE THREAD

**Issue by bmcmahen** [theKashey/react-remove-scroll#6]
First off, I love this library. It works, and it works well!

One feature request: I'd love the ability to prevent scrolling on the entire page -- including child components. Right now child components will permit scrolling. But it'd be great if we could optionally turn this off.

**Comment by theKashey** [comment]
Just create `RemoveScroll` somewhere _aside_ of your content. While it would allow scroll for the nested div - it would disable it for the rest of the page.
```js
const MyComponent = () => (
 <div>
   <RemoveScroll><div/></RemoveScroll>
   real content
 </div>   
)
```

**Comment by bmcmahen** [comment]
Oh man, haha. Of course! Thanks.
