### ISSUE TITLE
Yarn build failling

### ISSUE THREAD

**Issue by smguy9** [theKashey/react-remove-scroll#68]
Hi @theKashey,

Our builds started to fail today and this package seems to be latest to be updated.

![resim](https://user-images.githubusercontent.com/3155410/163804173-81f5440c-c3ca-497a-a3c9-f803f17ce692.png)

We are not directly using this package, it's a dependency on react-focus-on which is a dependency on @elastic/eui^39.1.1
![resim](https://user-images.githubusercontent.com/3155410/163804146-a28d888b-02d3-4b75-8856-cb2a1d0a17d8.png)

Do you have any ideas?

Thanks in advance.

**Comment by asaid-0** [comment]
I have the same issue

**Comment by cyzArea** [comment]
Me too

**Comment by viniciusmendite** [comment]
Eu também

**Comment by danielhessell** [comment]
Eu também

**Comment by m2hd1** [comment]
same issue, please make it a high priority 

![image](https://user-images.githubusercontent.com/16073350/163834038-43b0454a-0e02-439a-8269-ea005f4e25fd.png)

**Comment by bufordeeds** [comment]
Same issue

**Comment by asaid-0** [comment]
I installed an old version in my app dependencies and it worked

```"react-remove-scroll": "2.4.1"```

**Comment by theKashey** [comment]
:oof:

**Comment by theKashey** [comment]
2.5.0 has been deprecated
2.5.1 has been released with corrected entrypoints. That should fix the problem.

> Sorry everyone, used easter break to update all libraries and stopped on this library. It's quite hard to verify entrypoints without using a package from the "outside" and this is how this problem has been created.
