### ISSUE TITLE
Please upgrade @types/react 18.0.8

### ISSUE THREAD

**Issue by usercao** [theKashey/react-remove-scroll#69]
<img width="291" alt="image" src="https://user-images.githubusercontent.com/13760476/167377291-f1afdc6c-185b-4a6f-98f4-2a0fd0d3455e.png">

<img width="280" alt="image" src="https://user-images.githubusercontent.com/13760476/167377953-39e92a92-09a0-401b-a39a-f4c341dc2bf6.png">

**Comment by theKashey** [comment]
There is nothing I can do because everything has been already done - https://github.com/theKashey/react-remove-scroll/blob/master/package.json#L49

You might need to update package-lock a little bit.
