### ISSUE TITLE
Remove scroll from all parents

### ISSUE THREAD

**Issue by theKashey** [theKashey/react-remove-scroll#7]
Right now parent scrolling is disabled using JS, but scrollbars are not removed. While could.

**Comment by Zodiase** [comment]
Just letting you know, due to this issue, I'd not consider using this package (and `react-focus-on`, which I was just evaluating).

Would be excited to see improvements!

**Comment by theKashey** [comment]
On track 👍

**Comment by theKashey** [comment]
I haven't found a way how to __remove__ scroll from the parents. Look like that's just impossible.
But I've found a way how to __disable__ it

**Comment by theKashey** [comment]
Released as v2. To remove scroll from all parents - use `inert` property. But be careful - that's really ☠️stuff (working via `pointer-events` CSS property)
