### ISSUE TITLE
[Bug] Scrolling with mouse wheel in child textarea is disabled on Firefox

### ISSUE THREAD

**Issue by innub** [theKashey/react-remove-scroll#74]
## Bug
Scrolling with the mouse wheel in child textarea is incorrectly disabled on Firefox but works as expected on Chrome. 

## Expected
Scrolling with the mouse wheel in child textarea works on Firefox and Chrome.

<br>

Reproduction: https://codesandbox.io/s/gallant-tharp-b4qwzv?file=/src/App.js

The reason this happens and the workaround can be found here: https://github.com/radix-ui/primitives/issues/1417#issuecomment-1159809410

**Comment by theKashey** [comment]
🤔 why I check for `hidden` in one part and for `visible` in another 🤔 
I should have leave more comments

**Comment by theKashey** [comment]
🙇 found the reason (visible: Content is not clipped and may be rendered outside the padding box), and probably it's quite special to `textarea` for which "visible" still mean "has scrollbars"

I would check if using `scrollHeight` could be a better option here. In other case I would implement an edge case for text-area only (and there is already one for range inputs)
