### ISSUE TITLE
Pinch zoom does not work on MacOS when content is not scrollable or content is at `scrollTop` 0

### ISSUE THREAD

**Issue by chesterhow** [theKashey/react-remove-scroll#75]
## Bug
Even with the `allowPinchZoom` prop toggled to true, there are 2 cases where I am unable to pinch zoom on the content within `<RemoveScroll>` on MacOS using a trackpad (no issues on iOS and Android).

I've detailed the 2 cases below, but do let me know if I am perhaps misunderstanding the `allowPinchZoom` prop or using it incorrectly in some way 😅 

### 1. Content is not scrollable
- If the contents of `<RemoveScroll>` has no overflow and is not scrollable, I am unable to pinch zoom

https://codesandbox.io/s/react-remove-scroll-non-scrollable-content-unable-to-pinch-zoom-diiuw3

**Steps to repro:**
1. Pinch zoom on the content.
2. Pinch zoom does not work.
 
### 2. Content is scrollable but is at `scrollTop` 0
- If the contents of `<RemoveScroll>` has overflow, but has not been scrolled, I am unable to pinch zoom.

https://codesandbox.io/s/react-remove-scroll-scrolltop-0-unable-to-pinch-zoom-ezirwf

**Steps to repro:**
1. Pinch zoom on the content while it is not scrolled down.
2. Pinch zoom does not work.
3. Scroll content (by any amount)
4. Pinch zoom on the content.
5. Pinch zoom works.

**Comment by theKashey** [comment]
Thank you for such detailed description.
PinchZoom was designed/tested mostly for mobile phones (touch events) and probably not really working for trackpads.

**Comment by theKashey** [comment]
Confirmed - the current implementation cannot detect trackpad-based zoom and thinks that is a wheel event.
In order to support one might need to use [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events)

**Comment by atomiks** [comment]
`event.ctrlKey` on the `wheel` event determines if it's pinch-zoom or not, doing a code search in the repo returned 0 results so I assume it's not being checked for yet 😃

**Comment by theKashey** [comment]
On my machine `ctrlKey+wheel` is a system wide zoom, ie it works on the display level.

**Comment by atomiks** [comment]
I'm not sure what you mean, can you clarify? I think apps like Google Maps check for `event.ctrlKey` to determine pinch-zooming on a trackpad to zoom in vs. pan, so it should be reliable.

**Comment by theKashey** [comment]
@atomiks, sorry for a very long follow-up, and thank you for the very detailed page linked.
I hope this issue will be solved in the next release.

**Comment by theKashey** [comment]
Released in v2.6.0

**Comment by owenammann** [comment]
Can we update react focus on as well? :) https://github.com/theKashey/react-focus-on/pull/93
