### ISSUE TITLE
Ignored attempt to cancel a touchmove event with cancelable=false

### ISSUE THREAD

**Issue by StarpTech** [theKashey/react-remove-scroll#8]
hello, I see the error

```
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
```
in the console when I use touch events on the scrollable area.

This issue happens because https://github.com/theKashey/react-remove-scroll/blob/master/src/component.tsx#L101 can't be canceled!

A possible solution is described [here](https://stackoverflow.com/a/53315365)

**Comment by theKashey** [comment]
Is there an easy way to reproduce this problem?

**Comment by StarpTech** [comment]
Yes, use the chrome emulator in e.g iPad mode and scroll on the wrapped element.

**Comment by bmcmahen** [comment]
I've just noticed the same problem. FWIW, it doesn't actually seem to manifest in any bugs.

**Comment by theKashey** [comment]
And it's not reproducible for me (OSX, Chrome 74), including real mobile devices (testing iOS only, sorry).
I would say - don't trust Chrome Emulator here.

I'll use `.cancelable` in any case, but it's still open question how real is the problem.

**Comment by StarpTech** [comment]
> And it's not reproducible for me (OSX, Chrome 74), including real mobile devices (testing iOS only, sorry).
I would say - don't trust Chrome Emulator here.

> It does not result in any bug but with lots of errors in the console.

I think to rely on `cancelable` is the best solution for now.

**Comment by theKashey** [comment]
I saw many warning around canceling touch/scroll events, which __are__ cancelable, but _canceling them would lead to a bad used experience, bla, bla, bla_. But that's what we are doing here :)

**Comment by adrianparr** [comment]
What is the latest on this?

**Comment by Tumetsu** [comment]
I'm getting this same error when I have a dialog with horizontally scrollable element in it. The element seems to work fine on my Android phone but the console is filled with error on Chrome simulator.

Is there anything I could do on my app's side to avoid this or should I just shrug it off? I'm using this library as a dependency of reach ui's dialog component: https://github.com/reach/reach-ui

**Comment by theKashey** [comment]
I'll check `cancelable=false` events once again. It's more about - why they are not cancelable, that's the question.

**Comment by tschleuss** [comment]
Any news on this?

**Comment by theKashey** [comment]
Oof, time flies.

**Comment by thexpand** [comment]
Still occurs. Is there any resolution on this?

**Comment by thexpand** [comment]
I have updated my previous comment to include more insight on when it happens (at least for me).

**Comment by sabeenski** [comment]
Hello!
I am running into similar errors in my DataDog real user monitoring. The error is:

`IgnoredEventCancel: intervention: Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
`

Seems to be coming from `react-remove-scroll/dist/es2015/SideEffect.js at line 89`.

```
 if (sourceEvent && sourceEvent.should) {
            event.preventDefault();
            return;
        }
```

should we add a check here as well with `event. cancelable` ?

**Comment by csantos1113** [comment]
I'm facing the same issue. As @thexpand mentioned I'm able to reproduce this error with the same steps:

- Scroll all the way down and release the finger from the screen, then try to scroll down more: no error/warning
  

  https://user-images.githubusercontent.com/9648559/172483412-9c53aaa3-c932-464d-aa35-9383450ce9f8.mov




- Scroll up or down the screen and reach the end of the scrollable area, **but continue** dragging: error appear in the console

  https://user-images.githubusercontent.com/9648559/172483448-8fc08fe8-86bd-4ccf-a049-930278ea139d.mov
