### ISSUE TITLE
Apple Pencil

### ISSUE THREAD

**Issue by circlingthesun** [theKashey/react-remove-scroll#81]
I've implemented a modal wrapped in react-remove-scroll, and the library blocks all interactions with said modal when I'm using an Apple Pencil 2 on an IPad Pro on the latest IPadOS. I'm going to stop using this library for now, but I thought I'd report this incase anyone else experiences the same issue.

**Comment by theKashey** [comment]
Oh, that is a little unexpected behavior

**Comment by circlingthesun** [comment]
Not stale

**Comment by telriot** [comment]
Also bumping as I am facing the same issue with an hamburger menu implementation.
By the way, thanks for getting this set of libraries out, they are great!

**Comment by theKashey** [comment]
I still haven't found a moment to look into it. Any help would be appreciated.
