### ISSUE TITLE
Cannot pan when zoomed in on mobile (iOS tested so far)

### ISSUE THREAD

**Issue by richardwu** [theKashey/react-remove-scroll#91]
We are using chakra UI's modals which uses `RemoveScroll` [under the hook](https://github.com/chakra-ui/chakra-ui/blob/c57b00f80f177c2a165dc3e879e30e362b0806fb/packages/components/modal/src/modal-focus.tsx#L51-L57).

We have passed `allowPinchZoom`, which indeed does let users pinch and zoom on iOS.

However it doesn't let someone pan once zoomed it (tap + hold + drag).

**Comment by theKashey** [comment]
Yeah, that's a known bug without clear resolution.

**Comment by theKashey** [comment]
There is no answer right now, might be https://github.com/theKashey/react-focus-on/issues/49 will lead to one.
